require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-md

inherit_from: .rubocop_todo.yml

# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, AllowBeforeTrailingComments, ForceEqualSignAlignment.
Layout/ExtraSpacing:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, EnforcedStyleForExponentOperator.
# SupportedStylesForExponentOperator: space, no_space
Layout/SpaceAroundOperators:
  Enabled: true

# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - nmax.gemspec

# Configuration parameters: AllowedChars.
Style/AsciiComments:
  Enabled: false

# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, never
Style/FrozenStringLiteralComment:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  EnforcedStyle: ruby19

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: MinSize, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    # default: '[]'
    # '%i':    '()'
    '%w': '()'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*.rb'

# Configuration parameters: AggregateFailuresByDefault.
RSpec/MultipleExpectations:
  Enabled: false
